path: ./grass.png
name: "grass"
images:
  grass-tl:
    pos: 0,0
    size: 16,16
  grass-tcenter:
    pos: 16,0
    size: 16,16
  grass-tr:
    pos: 32,0
    size: 16,16
  grass-centerl:
    pos: 0,16
    size: 16,16
  grass-centercenter:
    pos: 16,16
    size: 16,16
  grass-centerr:
    pos: 32,16
    size: 16,16
  grass-bl:
    pos: 0,32
    size: 16,16
  grass-bcenter:
    pos: 16,32
    size: 16,16
  grass-br:
    pos: 32,32
    size: 16,16

  grass-deco-1:
    pos: 48,0
    size: 16,16
  grass-deco-2:
    pos: 64,0
    size: 16,16
  grass-deco-3:
    pos: 80,0
    size: 16,16
  grass-deco-4:
    pos: 48,16
    size: 16,16
  grass-deco-5:
    pos: 64,16
    size: 16,16

  grass-ramp-l:
    pos: 48,32
    size: 16,16
  grass-ramp-r:
    pos: 64,32
    size: 16,16
  grass-bend-bl:
    pos: 80,32
    size: 16,16
  grass-bend-br:
    pos: 96,32
    size: 16,16
